### ISSUE TITLE
Can't use it in Ubuntu

### ISSUE THREAD

**Issue by allenwoods** [CodeFalling/hexo-renderer-org#1]
I've getting the following error when attempting to install it in Ubuntu 14.04:
```shell
npm http GET https://registry.npmjs.org/org-js-for-hexo-renderer
npm http 304 https://registry.npmjs.org/org-js-for-hexo-renderer
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-51-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "org-js-for-hexo-renderer" "--save"
npm ERR! cwd /home/allenwoods/Code/allenwoods
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/allenwoods/Code/allenwoods/npm-debug.log
npm ERR! not ok code 0
 ```

I reinstall nodejs and npm
```shell
>> node -v & npm -v
v0.10.40
3.3.9
```
This time I got another error
```shell
npm ERR! Linux 3.16.0-51-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "org-js-for-hexo-renderer" "--save"
npm ERR! node v0.10.40
npm ERR! npm  v3.3.9
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/org-js-for-hexo-renderer
npm ERR! 404 
npm ERR! 404 'org-js-for-hexo-renderer' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/allenwoods/Code/allenwoods/npm-debug.log
```
So I try the git url
```shell
>> npm install https://github.com/CodeFalling/hexo-renderer-org.git --save
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported

> dtrace-provider@0.6.0 install /home/allenwoods/Code/allenwoods/node_modules/dtrace-provider
> node scripts/install.js

hexo-site@0.0.0 /home/allenwoods/Code/allenwoods
├─┬ hexo@3.1.1
│ └─┬ bunyan@1.5.1
│   └─┬ dtrace-provider@0.6.0 
│     └── nan@2.1.0 
└─┬ hexo-renderer-org@0.0.3  (git+https://github.com/CodeFalling/hexo-renderer-org.git#51eee3827abab015a6b66832b50c062141d9856b)
  └── org@0.2.0 
```
then I create a new post and run hexo
```shell
hexo g
<h2 id="header-1">Orgmode</h2>
<h3 id="header-1-1">Why orgmode</h3>
我编不下去了。。

FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Unmatched 'end' directive for example at line 1
    at Object.Parser.createErrorReport (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:52:12)
    at Object.Parser.parseDirective (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:371:18)
    at Object.Parser.parseElement (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:142:22)
    at Object.Parser.parseElement (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:134:26)
    at Object.Parser.parseNodes (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:84:26)
    at Object.Parser.parseDocument (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:79:10)
    at Object.Parser.parse (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:46:10)
    at Hexo.render (/home/allenwoods/Code/allenwoods/node_modules/hexo-renderer-org/index.js:5:30)
    at /home/allenwoods/Code/allenwoods/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:448:13)
```

Since I've learned little about nodejs, I can't figure out what's wrong, please help me:scream: THX!

**Comment by CodeFalling** [comment]
My fault！I just forget to publish the right version to npm.I will do it after about one hour.
So sorry for this.

**Comment by allenwoods** [comment]
Actually, I found that even there is no posts at all in the `_posts` folder, the error message 
```shell
Error: Unmatched 'end' directive for example at line 1
...
```
will still appear

**Comment by CodeFalling** [comment]
New version published to npm now.
```shell
npm uninstall --save  hexo-renderer-org
npm install --save  hexo-renderer-org
```
should fix

**Comment by allenwoods** [comment]
```shell
➤ hexo g
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Unmatched 'end' directive for example at line 1
    at Object.Parser.createErrorReport (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:52:12)
    at Object.Parser.parseDirective (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:371:18)
    at Object.Parser.parseElement (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:142:22)
    at Object.Parser.parseElement (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:134:26)
    at Object.Parser.parseNodes (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:84:26)
    at Object.Parser.parseDocument (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:79:10)
    at Object.Parser.parse (/home/allenwoods/Code/allenwoods/node_modules/org/lib/org/parser.js:46:10)
    at Hexo.render (/home/allenwoods/Code/allenwoods/node_modules/hexo-renderer-org/index.js:5:30)
    at /home/allenwoods/Code/allenwoods/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:448:13)
```
Fatal Error still exist after updating the render

**Comment by allenwoods** [comment]
Problems Solved !
Has to remove some old org files to make it works
