### ISSUE TITLE
Plugin load failed: hexo-renderer-org

### ISSUE THREAD

**Issue by xushaobo** [CodeFalling/hexo-renderer-org#19]
ERROR Plugin load failed: hexo-renderer-org
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (/home/rosa/Documents/Gitblog/node_modules/hexo/lib/hexo/index.js:213:21)
    at /home/rosa/Documents/Gitblog/node_modules/hexo-renderer-org/index.js:2:16
    at /home/rosa/Documents/Gitblog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:630:18)
    at /home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at fs.js:266:14
    at /home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/rosa/Documents/Gitblog/node_modules/hexo/node_modules/warehouse/node_modules/graceful-fs/graceful-fs.js:43:10
    at /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at Object.oncomplete (fs.js:107:15)

**Comment by CodeFalling** [comment]
See https://github.com/CodeFalling/hexo-renderer-org/issues/9
