### ISSUE TITLE
Error happend with `,#+BEGIN_SRC`

### ISSUE THREAD

**Issue by allenwoods** [CodeFalling/hexo-renderer-org#2]
Error happened while I generate from a org-file contain a line `,#+BEGIN_SRC`
```shell
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Unmatched 'end' directive for src at line 32
    at Object.Parser.createErrorReport (/home/allenwoods/Code/allenwoods/node_modules/hexo-renderer-org/node_modules/org/lib/org/parser.js:52:12)
    at Object.Parser.parseDirective (/home/allenwoods/Code/allenwoods/node_modules/hexo-renderer-org/node_modules/org/lib/org/parser.js:371:18)
    at Object.Parser.parseElement (/home/allenwoods/Code/allenwoods/node_modules/hexo-renderer-org/node_modules/org/lib/org/parser.js:142:22)
    at Object.Parser.parseNodes (/home/allenwoods/Code/allenwoods/node_modules/hexo-renderer-org/node_modules/org/lib/org/parser.js:84:26)
    at Object.Parser.parseDocument (/home/allenwoods/Code/allenwoods/node_modules/hexo-renderer-org/node_modules/org/lib/org/parser.js:79:10)
    at Object.Parser.parse (/home/allenwoods/Code/allenwoods/node_modules/hexo-renderer-org/node_modules/org/lib/org/parser.js:46:10)
    at Hexo.render (/home/allenwoods/Code/allenwoods/node_modules/hexo-renderer-org/index.js:6:30)
    at /home/allenwoods/Code/allenwoods/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/allenwoods/Code/allenwoods/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:448:13)

```
After removing the comma everything became fine.

**Comment by CodeFalling** [comment]
Use `emacs` branch instead.
