### ISSUE TITLE
I see closed  issue #9 , but  always "ERROR Plugin load failed: hexo-renderer-org"

### ISSUE THREAD

**Issue by john321123** [CodeFalling/hexo-renderer-org#24]
Hi

I see closed  issue #9 , but  Plugin load failed

configure as follow:
npm@1.4.3
.nvm/v0.10.26
hexo: 3.2.2
hexo-cli: 1.0.2
os: Linux 4.4.8 linux x64
http_parser: 1.0
node: 0.10.26
v8: 3.14.5.9
ares: 1.9.0-DEV
uv: 0.10.25
zlib: 1.2.3
modules: 11
openssl: 1.0.1e

/home/john/github.local/blog/node_modules/hexo-renderer-org/lib/renderer.js:31
  return new Promise((reslove, reject) => {
                                        ^
ERROR Plugin load failed: hexo-renderer-org
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (/home/john/github.local/blog/node_modules/hexo/lib/hexo/index.js:213:21)
    at /home/john/github.local/blog/node_modules/hexo-renderer-org/index.js:2:16
    at /home/john/github.local/blog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/home/john/github.local/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/john/github.local/blog/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/john/github.local/blog/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/john/github.local/blog/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/john/github.local/blog/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/home/john/github.local/blog/node_modules/bluebird/js/release/promise.js:630:18)
    at Promise._resolveCallback (/home/john/github.local/blog/node_modules/bluebird/js/release/promise.js:425:57)
    at Promise._settlePromiseFromHandler (/home/john/github.local/blog/node_modules/bluebird/js/release/promise.js:516:17)
    at Promise._settlePromise (/home/john/github.local/blog/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/john/github.local/blog/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/john/github.local/blog/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/home/john/github.local/blog/node_modules/bluebird/js/release/promise.js:630:18)
    at /home/john/github.local/blog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/john/github.local/blog/node_modules/graceful-fs/graceful-fs.js:78:16
    at fs.js:266:14
    at /home/john/github.local/blog/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/john/.nvm/v0.10.26/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at Object.oncomplete (fs.js:107:15)
INFO  Start processing
INFO  Files loaded in 2.07 s

**Comment by CodeFalling** [comment]
You have to upgrade your nodejs

**Comment by john321123** [comment]
the nodejs v0.10.26 
and stable v6.4.0
