### ISSUE TITLE
js lambda错误？怎么解决

### ISSUE THREAD

**Issue by fangpin** [CodeFalling/hexo-renderer-org#26]
ERROR Plugin load failed: hexo-renderer-org
/Users/fangpin/blog/node_modules/hexo-renderer-org/lib/renderer.js:31
  return new Promise((reslove, reject) => {
                                       ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/fangpin/blog/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/fangpin/blog/node_modules/hexo-renderer-org/index.js:2:16
    at /Users/fangpin/blog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/fangpin/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/fangpin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/fangpin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/fangpin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/fangpin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/fangpin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Users/fangpin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Users/fangpin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Users/fangpin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/fangpin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/fangpin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/fangpin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at /Users/fangpin/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/fangpin/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at fs.js:334:14
    at /Users/fangpin/blog/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/fangpin/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/fangpin/blog/node_modules/hexo/node_modules/warehouse/node_modules/graceful-fs/graceful-fs.js:43:10
    at /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:95:15)
INFO  Start processing
INFO  Files loaded in 220 ms
INFO  0 files generated in 217 ms
INFO  Deploying: git
INFO  Setting up Git deployment... #

**Comment by CodeFalling** [comment]
升级 nodejs 版本即可

**Comment by fangpin** [comment]
@CodeFalling thx
