### ISSUE TITLE
after install hexo-renderer-org, hexo server go with error

### ISSUE THREAD

**Issue by angry-bird** [CodeFalling/hexo-renderer-org#34]
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troub
leshooting.html                                                                        
Template render error: (unknown path) [Line 81, Column 52]
  parseSignature: expected comma after expression
    at Object.exports.prettifyError (/Users/mable/Dropbox/emacs/web/blog/node_modules/nu
njucks/src/lib.js:34:15)                                                               
    at new_cls.render (/Users/mable/Dropbox/emacs/web/blog/node_modules/nunjucks/src/env
ironment.js:469:27)                                                                    
    at new_cls.renderString (/Users/mable/Dropbox/emacs/web/blog/node_modules/nunjucks/s
rc/environment.js:327:21)                                                              
    at /Users/mable/Dropbox/emacs/web/blog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/mable/Dropbox/emacs/web/blog/node_modules/bluebird/js/re
lease/debuggability.js:300:9)                                                          
    at Promise._resolveFromExecutor (/Users/mable/Dropbox/emacs/web/blog/node_modules/bl
uebird/js/release/promise.js:481:18)                                                   
    at new Promise (/Users/mable/Dropbox/emacs/web/blog/node_modules/bluebird/js/release
/promise.js:77:14)                                                                     
    at Tag.render (/Users/mable/Dropbox/emacs/web/blog/node_modules/hexo/lib/extend/tag.
js:64:10)                                                                              
    at Object.tagFilter [as onRenderEnd] (/Users/mable/Dropbox/emacs/web/blog/node_modul
es/hexo/lib/hexo/post.js:253:16)                                                       
    at /Users/mable/Dropbox/emacs/web/blog/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/mable/Dropbox/emacs/web/blog/node_modules/bluebird/js/release/
util.js:16:23)                                                                         
    at Promise._settlePromiseFromHandler (/Users/mable/Dropbox/emacs/web/blog/node_modul
es/bluebird/js/release/promise.js:510:31)                                              
    at Promise._settlePromise (/Users/mable/Dropbox/emacs/web/blog/node_modules/bluebird
/js/release/promise.js:567:18)                                                         
    at Promise._settlePromise0 (/Users/mable/Dropbox/emacs/web/blog/node_modules/bluebir
d/js/release/promise.js:612:10)                                                        
    at Promise._settlePromises (/Users/mable/Dropbox/emacs/web/blog/node_modules/bluebir
d/js/release/promise.js:691:18)     
at Async._drainQueue (/Users/mable/Dropbox/emacs/web/blog/node_modules/bluebird/js/r
elease/async.js:133:16)                                                                
    at Async._drainQueues (/Users/mable/Dropbox/emacs/web/blog/node_modules/bluebird/js/
release/async.js:143:10)                                                               
    at Immediate.Async.drainQueues (/Users/mable/Dropbox/emacs/web/blog/node_modules/blu
ebird/js/release/async.js:17:14)                                                       
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)                             
```

**Comment by CodeFalling** [comment]
What's the version of your nodejs?

**Comment by angry-bird** [comment]
Appreciate your time. 
My mac is running the OSX10.9, and node v7.3.0, npm 3.10.10
