### ISSUE TITLE
hexo g 报错

### ISSUE THREAD

**Issue by xushaobo** [CodeFalling/hexo-renderer-org#41]
/home/xu/blog/node_modules/hexo-renderer-org/lib/renderer.js:31
  return new Promise((reslove, reject) => {
                                        ^
ERROR Plugin load failed: hexo-renderer-org
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (/home/xu/blog/node_modules/hexo/lib/hexo/index.js:213:21)
    at /home/xu/blog/node_modules/hexo-renderer-org/index.js:2:16
    at /home/xu/blog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/home/xu/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/xu/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/xu/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/xu/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/xu/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/xu/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/home/xu/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/home/xu/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/home/xu/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/xu/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/xu/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/home/xu/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at /home/xu/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/xu/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at fs.js:268:14
    at /home/xu/blog/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/xu/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at /home/xu/blog/node_modules/hexo/node_modules/warehouse/node_modules/graceful-fs/graceful-fs.js:43:10
    at /usr/local/lib/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
    at Object.oncomplete (fs.js:107:15)

**Comment by CodeFalling** [comment]
升级 nodejs 版本即可。
