### ISSUE TITLE
无法解析Tag了。

### ISSUE THREAD

**Issue by young40** [CodeFalling/hexo-renderer-org#56]
```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: data.setTags is not a function
    at read_tags (/Users/young40/Work/www.young40.com/node_modules/hexo-renderer-org/lib/read-info.js:48:12)
    at read_all (/Users/young40/Work/www.young40.com/node_modules/hexo-renderer-org/lib/read-info.js:78:5)
    at Hexo.read_info (/Users/young40/Work/www.young40.com/node_modules/hexo-renderer-org/lib/read-info.js:10:3)
    at Hexo.tryCatcher (/Users/young40/Work/www.young40.com/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/young40/Work/www.young40.com/node_modules/bluebird/js/release/method.js:15:34)

```

版本信息
```
hexo: 3.3.7
hexo-cli: 1.0.3
os: Darwin 16.6.0 darwin x64
http_parser: 2.7.0
node: 8.1.3
v8: 5.8.283.41
uv: 1.12.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
```

**Comment by frapples** [comment]
我研究了一下，觉得这是一个不可能发生的问题啊

你能提高下触发bug的org文件吗？是特定的org文件才会触发，还是你所有的org文件都这样？
